### ISSUE TITLE
在并发连接请求时，报fatal error: concurrent map writes

### ISSUE THREAD

**Issue by berkaroad** [Berkaroad/saashard#11]
```
fatal error: concurrent map writes

goroutine 166 [running]:
runtime.throw(0x24b877, 0x15)
    /usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:566 +0x95 fp=0xc420203c58 sp=0xc420203c38
runtime.mapdelete(0x207ce0, 0xc420077740, 0xc42028c2e4)
    /usr/local/Cellar/go/1.7.1/libexec/src/runtime/hashmap.go:572 +0x28d fp=0xc420203cb8 sp=0xc420203c58
github.com/berkaroad/saashard/proxy.(*ClientConn).Close(0xc42028c2a0, 0x1, 0x1)
    /Users/berkaroad/go/src/github.com/berkaroad/saashard/proxy/conn.go:225 +0x1ab fp=0xc420203da0 sp=0xc420203cb8
github.com/berkaroad/saashard/proxy.(*ClientConn).dispatch(0xc42028c2a0, 0xc420073c1c, 0x1, 0x1, 0x0, 0x0)
    /Users/berkaroad/go/src/github.com/berkaroad/saashard/proxy/conn.go:236 +0x32e fp=0xc420203e30 sp=0xc420203da0
github.com/berkaroad/saashard/proxy.(*ClientConn).Run(0xc42028c2a0)
    /Users/berkaroad/go/src/github.com/berkaroad/saashard/proxy/conn.go:182 +0xd5 fp=0xc420203f08 sp=0xc420203e30
github.com/berkaroad/saashard/proxy.(*Server).onConn(0xc4200b6380, 0x350840, 0xc42007c030)
    /Users/berkaroad/go/src/github.com/berkaroad/saashard/proxy/proxy.go:205 +0x2c8 fp=0xc420203f88 sp=0xc420203f08
runtime.goexit()
    /usr/local/Cellar/go/1.7.1/libexec/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420203f90 sp=0xc420203f88
created by github.com/berkaroad/saashard/proxy.(*Server).Run
    /Users/berkaroad/go/src/github.com/berkaroad/saashard/proxy/proxy.go:159 +0x14c
```

**Comment by berkaroad** [comment]
采用同步锁，解决操作proxy中的conns时的并发冲突问题，目前bug已修复
